Support `actor` object conforming to `Actor` protocol
uber/mockolo pull request #222
Opened 2023-03-09 16:53 UTC by treastrain

# Issue
Part of #216
(https://github.com/uber/mockolo/issues/216#issuecomment-1454179318 's "2.")

# Description
Add feature generating mocks for that protocol that conform to the [`Actor`](https://developer.apple.com/documentation/swift/actor) automatically become actor.

For details: https://github.com/uber/mockolo/issues/216#issuecomment-1454179318

2023-03-09 16:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber/mockolo?pullRequest=222) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber/mockolo?pullRequest=222) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber/mockolo?pullRequest=222) it.</sub>

2023-03-10 13:05 UTC, uhooi requested changes
Thx PR!!

2023-03-10 13:05 UTC, uhooi commented on Tests/TestActorMocking/FixtureMockableActor.swift
> +/// \(String.mockAnnotation)
I would also like you to write the following test.

```swift
/// \(String.mockAnnotation)
protocol Foo: Bar {
    func foo(arg: String) async -> Result<String, Error>
    var bar: Int { get }
}

protocol Bar: Actor {
    func baz(arg: String) async -> Result<String, Error>
    var qux: Int { get }
}
```

2023-03-13 07:33 UTC, treastrain commented on Tests/TestActorMocking/MockActorTests.swift
> +}
or use `XCTSkip`

2023-03-13 07:34 UTC, uhooi commented
@treastrain 
The test is failing in Xcode 12.
Since Swift Concurrency (async/await, Actor etc) is available from Xcode 13, please skip the test in Xcode 12.

```
Test Suite 'MockActorTests' started at 2023-03-10 13:00:08.892
Test Case '-[MockoloTests.MockActorTests testActorProtocol]' started.
/Users/runner/work/mockolo/mockolo/Tests/MockoloTestCase.swift:154: error: -[MockoloTests.MockActorTests testActorProtocol] : XCTAssertTrue failed
Test Case '-[MockoloTests.MockActorTests testActorProtocol]' failed (1.854 seconds).
Test Suite 'MockActorTests' failed at 2023-03-10 13:00:10.746.
	 Executed 1 test, with 1 failure (0 unexpected) in 1.854 (1.854) seconds
```

ref: https://github.com/uber/mockolo/actions/runs/4376819642/jobs/7676406579#step:5:251

2023-03-13 09:28 UTC, sidepelican requested changes
I can say the same things with https://github.com/uber/mockolo/pull/221 . See it.

2024-10-02 10:11 UTC, acevif commented
Hi,

I'm really interested in this feature and looking forward to its potential inclusion.
Thank you for your work on this!

2024-10-24 02:34 UTC, treastrain commented
I'm sorry. I have been away for a long time since I made this pull request.

I will defer the rest of this to #266.

2024-10-24 02:34 UTC, closed without merging