Compilation fix for a mock where the return type of a closure is an opaque type
uber/mockolo pull request #259
Opened 2024-04-26 20:54 UTC by omarzl

The following code:

```
protocol ProtocolReturningOpaqueTypeInClosureProtocol {
    func register(router: @autoclosure @escaping () -> (some Error))
}
```

produces this mock:
```
class ProtocolReturningOpaqueTypeInClosureProtocolMock: ProtocolReturningOpaqueTypeInClosureProtocol {
    init() { }
    private(set) var registerCallCount = 0
    var registerHandler: ((@autoclosure @escaping () -> (some Error)) -> ())?
    func register(router: @autoclosure @escaping () -> (some Error))  {
        registerCallCount += 1
        if let registerHandler = registerHandler {
            registerHandler(router())
        }
    }
}
```

causing the compilation error:
`'some' cannot appear in parameter position in result type '((@autoclosure @escaping () -> (some Error)) -> ())?'`

This pr fixes the variable `registerHandler` by generating the following mock:
```
class ProtocolReturningOpaqueTypeInClosureProtocolMock: ProtocolReturningOpaqueTypeInClosureProtocol {
    init() { }
    private(set) var registerCallCount = 0
    var registerHandler: ((@autoclosure @escaping () -> (any Error)) -> ())?
    func register(router: @autoclosure @escaping () -> (some Error))  {
        registerCallCount += 1
        if let registerHandler = registerHandler {
            registerHandler(router())
        }
    }
}
```

2024-04-26 20:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber/mockolo?pullRequest=259) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber/mockolo?pullRequest=259) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber/mockolo?pullRequest=259) it.</sub>

2024-04-27 12:44 UTC, sidepelican reviewed
I wonder if this implementation would work well with the following code?🤔

```swift
protocol P {
     func f(_: () -> (MyAwesomeType))
}
```

2024-04-29 15:54 UTC, omarzl commented
> I wonder if this implementation would work well with the following code?🤔


Hello, I am only replacing the word `some` to `any` when the return type is `some MyType`

These other examples work well:

```
protocol Foo {
    func register(router: () -> (Bar))
    func register<T>(router: () -> (T))
}

protocol Bar {}
```
The generated mocks are:
```
var registerRouterHandler: ((() -> (Bar)) -> ())?
var registerRouterTHandler: ((() -> (Any)) -> ())?
```

2024-04-30 01:37 UTC, sidepelican requested changes
I've confirmed that `MyAwesomeType` changes to `MyAweanyType`.
It seems sufficient to just change the replacement logic to `s/some /any /g`.

2024-04-30 17:43 UTC, omarzl commented
oh right, sorry I misunderstood you
I updated the fix and the tests to consider this scenario, thanks!

2024-05-02 02:57 UTC, sidepelican approved these changes
Maybe work with most codes. Thanks!

2024-05-02 02:58 UTC, sidepelican commented
Sorry I forgot launch workflow.

2024-05-02 02:59 UTC, merged